size_t Length(const char* str);
bool IsNullOrEmpty(const char* str);
bool Equal(const char* lStr, const char* rStr);
char* FillString(const char* str, const char target);
char* FillString(const char* str, const char target, const size_t start, const size_t count);
char* NewString(const size_t length);
char* NewString(const size_t length, const char target);
char* EmptyString();
char* Copy(const char* str);
char* Join(const char* str0, const char* str1);
char* Join(const char* str0, const char* str1, const char* str2);
size_t IndexOf(const char* str, const char* target);
size_t IndexOf(const char* str, const char* target, const size_t start);
size_t LastIndexOf(const char* str, const char* target);
size_t LastIndexOf(const char* str, const char* target, const size_t start);
char* Reverse(const char* str);
char* Remove(const char* str, const size_t start, const size_t count);
char* Insert(const char* str, const char* target, const size_t index);
char* Replace(const char* str, const char* from, const char* to);
char* Replace(const char* str, const char* from, const char* to, const size_t count);
char* TrimStart(const char* str, const size_t count);
char* TrimStart(const char* str, const char target);
char* TrimEnd(const char* str, const size_t count);
char* TrimEnd(const char* str, const char target);
bool Contains(const char* str, const char* target);
bool StartsWith(const char* str, const char* target);
bool EndsWith(const char* str, const char* target);
char* GetStringAt(const char* str, const size_t start, const size_t end);
char* Substring(const char* str, const size_t start, const size_t count);
char* ToString(const char x);
char* ToString(const int x);
char ToLower(const char x);
char ToUpper(const char x);
bool IsAlphanumeric(const char x);
bool IsAlphabet(const char x);
bool IsNumber(const char x);
bool IsHex(const char x);
bool IsControl(const char x);
bool IsUpper(const char x);
bool IsLower(const char x);
char* ToLower(const char* str);
char* ToUpper(const char* str);
bool IsNumber(const char* str);
bool IsAlphanumeric(const char* str);
bool IsAlphabet(const char* str);
bool IsHex(const char* str);
bool IsControl(const char* str);
bool IsUpper(const char* str);
bool IsLower(const char* str);